export const dasboardStyles = {
  contentPaper: {
    height: 670,
    maxWidth: "40vw",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    padding: 3,
    border: "1px solid #E2E8F0",
  },
  donutGrid: {
    height: "250px",
    width: "250px",
    display: "flex",
    justifyContent: "center",
  },
  scoreText: { fontSize: "small", marginRight: 2 },
  revenuePaper: {
    height: "70px",
    width: "90px",
    marginTop: 1,
    backgroundColor: "#F8FAFC",
    fontWeight: 600,
    boxShadow: "none",
    padding: 3,
  },
  revenueText: { color: "#94A3B8", fontSize: "12px" },
  pieGrid: {
    height: "250px",
    width: "250px",
    display: "flex",
    justifyContent: "center",
  },
  footerCard: {
    height: "179px",
    width: "222px",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-evenly",
    alignItems: "center",
    padding: 3,
    border: "1px solid #E2E8F0",
  },
};
